schema_version = "1.0.0"

id = "link_parents"
version = "1.1.0-beta"
name = "Link Parents"
tagline = "Link objects parents & edit Parent Inverse Matrix in UI"
maintainer = "Lukas Sabaliauskas <lukas_sabaliauskas@hotmail.com>"
type = "add-on"
tags = ["Object", "Rigging", "User Interface"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]